# name: Deploy Webapp to Prod
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - webapp/**
#       - .github/workflows/firebase-hosting-main.yml
#       - firebase.json
#       - .firebaserc
#   workflow_dispatch:

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     env:
#       VITE_FIREBASE_CONFIG_FULL: "${{ vars.VITE_FIREBASE_CONFIG_PROD }}"
#     steps:
#       - uses: actions/checkout@v4
#       - name: "Install and Build"
#         run: (npm ci && npm run build)
#         working-directory: webapp
#       - uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: "${{ secrets.GITHUB_TOKEN }}"
#           firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EACH_MOMENT }}"
#           channelId: live
#           projectId: each-moment-warehouse
